# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a449dfdff6c52805dcdf74296dcf28130c761f64de63c037044c36bf3540aece42a9c03839eb02bc857a62bd6f1c49749719654afdadf30d00cedf25d23d596c

test:
  secret_key_base: 01134399b462738167b99686b836074efb202f171957fbbdaa4193e40218cf1c197f01bab9d78d080ac486231834f8a7cf317ded7db9e3a073f980f6c885e4bf

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
